## Optimizer Block
general:
  optimizer: bayesian_optimization
  code_type: nuscale_database
  results_directory_name: output_files

optimization:
  population_size: 30
  batch_size: 3
  number_of_generations: 50
  objectives:
    max_boron:
      goal: less_than_target
      target: 1300
      weight: 1.0
    PinPowerPeaking:
      goal: less_than_target
      weight: 400.0 
      target: 2.1
    FDeltaH:
      goal: less_than_target
      target: 1.48
      weight: 600.0     
    cycle_length:
      goal: maximize
      weight: 1.00
## Algorithm Settings
algorithm:
  acquisition_function: gp_hedge

## Fuel Assembly Parts
assembly_options:
  reflectors:
    NSFA:
      refl_type: all
      serial: None
  blankets:
    None:
      serial: None
  fuel: 
    NSFA23: 
      type: 2
      serial: None
      blanket: None
    NSFA23GAD: 
      type: 3
      serial: None
      blanket: None
    NSFA39: 
      type: 4
      serial: None
      blanket: None
    NSFA39GAD: 
      type: 5
      serial: None
      blanket: None
    NSFA455: 
      type: 6
      serial: None
      blanket: None
    NSFA455GAD: 
      type: 7
      serial: None
      blanket: None

## Genome
decision_variables:
  # parameters used to fill each chromosome.
  parameters:
    NSFA23:
      map: &ID001
        [1,
         1, 1,
         1, 1, 1,
         1, 1]
    NSFA23GAD:
      map: *ID001 #this is natively interpreted by yaml, which is super nice.
    NSFA39:
      map: *ID001
    NSFA39GAD:
      map: *ID001
    NSFA455:
      map: *ID001
    NSFA455GAD:
      map: *ID001
