## Optimizer Block
optimization:
  methodology: bayesian_optimization
  code_type: nuscale_database
  data_type: single cycle
  results_directory_name: output_files
  population_size: 30
  batch_size: 5
  number_of_generations: 300
  solution_symmetry: octant #chromosome symmetry
  objectives:
    max_boron:
      goal: less_than_target
      target: 1300
      weight: 1.0
    PinPowerPeaking:
      goal: less_than_target
      weight: 400.0 
      target: 2.1
    FDeltaH:
      goal: less_than_target
      target: 1.48
      weight: 600.0     
    cycle_length:
      goal: maximize
      weight: 1.00

## Algorithm Settings
algorithm:
  acquisition_function: gp_hedge

## Fuel Assembly Parts
assembly_options:
  fuel: 
    NSFA23: 
      type: 2
    NSFA23GAD: 
      type: 3
    NSFA39: 
      type: 4
    NSFA39GAD: 
      type: 5
    NSFA455: 
      type: 6
    NSFA455GAD: 
      type: 7

## Genome
decision_variables:
  # parameters used to fill each chromosome.
  parameters:
    NSFA23:
      map: &ID001
        [1,
         1, 1,
         1, 1, 1,
         1, 1]
    NSFA23GAD:
      map: *ID001 #this is natively interpreted by yaml, which is super nice.
    NSFA39:
      map: *ID001
    NSFA39GAD:
      map: *ID001
    NSFA455:
      map: *ID001
    NSFA455GAD:
      map: *ID001