## Optimizer Block
optimization:
  methodology: bayesian_optimization
  code_type: nuscale_database
  data_type: single cycle
  results_directory_name: output_files
  population_size: 30
  batch_size: 5
  number_of_generations: 300
  solution_symmetry: octant #chromosome symmetry
  objectives:
    max_boron:
      goal: less_than_target
      target: 1300
      weight: 1.0
    PinPowerPeaking:
      goal: less_than_target
      weight: 400.0 
      target: 2.1
    FDeltaH:
      goal: less_than_target
      target: 1.48
      weight: 600.0     
    cycle_length:
      goal: maximize
      weight: 1.00

## Algorithm Settings
algorithm:
  acquisition_function: gp_hedge

## Fuel Assembly Parts
assembly_options:
  reflectors:
    FA420REFL:
      refl_type: all #all, radial, top, or bottom
      serial: stp_FA420REFL
  blankets:
    FA260BLANKET:
      serial: stp_FA260BLANKET
  fuel: 
    FA420IFBA064: 
      type: 20
    FA420IFBA104: 
      type: 30
    FA420IFBA128: 
      type: 40
    FA460IFBA128: 
      type: 50

## Genome
decision_variables:
  # parameters used to fill each chromosome.
  parameters:
    2:
      map: &ID001
        [1,
         1, 1,
         1, 1, 1,
         1, 1]
    3:
      map: *ID001 #this is natively interpreted by yaml, which is super nice.
    4:
      map: *ID001
    5:
      map: *ID001
    6:
      map: *ID001
    7:
      map: *ID001
